### PR TITLE
[MERGE ME FIRST, PLEASE] Add a few CSS interfaces.

### PR DESCRIPTION
**Pull request by jpmedley**
@vinyldarkscratch can you please prioritize the CSS PRs ahead of the one's I did on 11/12?

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
I'll be able to get these once the collector project has released its 1.0!

**Comment by jpmedley** [comment]
When will that be?

**Comment by jpmedley** [comment]
@vinyldarkscratch @foolip When do you plan to release 1.0? I need to get this merged and deployed sooner rather than later.

Haven't you submitted files from the collector already?

**Comment by foolip** [comment]
The collector is already at version 1.1.3. @vinyldarkscratch can you update these APIs?

**Comment by vinyldarkscratch** [comment]
Got the real versions and submitted as https://github.com/mdn/browser-compat-data/pull/7434!

**Comment by jpmedley** [comment]
Thank you both.

**Pull request closed without merging**
